#!/usr/bin/env python3
"""Generate `docs/test-suite.md` from the corpus.

The documentation is produced from the cases rather than written alongside them, so it
cannot drift: every test is described by its own `title` and `rationale`, and a case that
loses its rationale shows up here as a hole rather than quietly going undocumented.

    tests/suite/gen-docs.py            # write docs/test-suite.md
    tests/suite/gen-docs.py --check    # fail if the committed file is out of date
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

SUITE = Path(__file__).resolve().parent
REPO = SUITE.parent.parent
OUTPUT = REPO / "docs" / "test-suite.md"
BEHAVIOUR = REPO / "docs" / "original-behaviour.md"

AREA_INTROS = {
    "axis-syntax": (
        "What happens to the text someone types into an axis cell. This is the tool's "
        "entire input language — a blank cell, a number, or a `min:max` range — so it is "
        "also where a mistyped entry either gets caught or turns into a font nobody asked "
        "for."
    ),
    "static-instancing": (
        "Pinning every axis, which is what most people come to Slice for: one weight, "
        "frozen, ready to hand to a design application. The output has no axes left, so "
        "everything that described variation has to go, and everything that described the "
        "font's identity has to be brought up to date."
    ),
    "partial-instancing": (
        "Narrowing the design space while the font stays variable — fewer axes, or the "
        "same axes over smaller ranges. Harder than pinning, because the variation data "
        "has to be rewritten to say the same thing about a smaller space rather than "
        "simply discarded."
    ),
    "names": (
        "The nine `name` records the editor exposes, and what happens to the ones it does "
        "not. A font's names are how an operating system groups it into a family, so "
        "losing one is not cosmetic."
    ),
    "bitflags": (
        "`OS/2.fsSelection` and `head.macStyle`: the bits that tell software whether a "
        "font is regular, bold or italic. Six of them are editable; the rest must survive "
        "untouched."
    ),
    "outlines-containers": (
        "The glyphs themselves, the removal of overlapping contours, and the file formats "
        "the result can be written in."
    ),
}


def load_cases() -> list[dict]:
    cases = []
    for path in sorted((SUITE / "cases").glob("*.json")):
        if path.name.startswith("_"):
            continue
        data = json.loads(path.read_text())
        for case in data.get("cases", []):
            case["_area"] = data.get("area", path.stem)
            cases.append(case)
    return cases


def claim_titles() -> dict[str, str]:
    """Pull the one-line statement of each claim out of the behaviour map."""
    if not BEHAVIOUR.exists():
        return {}
    titles = {}
    text = BEHAVIOUR.read_text()
    for match in re.finditer(r"^\*\*([A-Z]\d+)\*\*\s*·?\s*`?(\w[\w-]*)`?\s*·?\s*(.+?)$", text, re.M):
        claim, _cls, statement = match.groups()
        titles[claim] = statement.strip().rstrip(".")
    return titles


def render(cases: list[dict]) -> str:
    titles = claim_titles()
    by_area: dict[str, list[dict]] = defaultdict(list)
    for case in cases:
        by_area[case["_area"]].append(case)

    classes = Counter(c.get("class", "unclassified") for c in cases)
    needs_feature = sum(1 for c in cases if c.get("original_lacks_feature"))

    out: list[str] = []
    w = out.append

    w("# The conformance test suite, in plain English")
    w("")
    w("<!-- Generated by tests/suite/gen-docs.py. Edit the cases, not this file. -->")
    w("")
    w("This describes every test in the corpus and why it is there. It is generated from")
    w("the cases themselves, so it cannot fall out of step with them.")
    w("")
    w("## What this suite is for")
    w("")
    w("Slice takes a variable font and gives you a smaller one. There are two programs")
    w("that do this: the original PyQt5 application by Source Foundry, and this")
    w("reimplementation. The suite exists to say, precisely and testably, what such a")
    w("program *should* do — and then to hold both of them to it.")
    w("")
    w("The cases are data, not code. The same case runs against both programs, and a")
    w("single shared checker evaluates the result, so neither program marks its own")
    w("homework and no test can be quietly written in a way that flatters one of them.")
    w("")
    w("Where the two disagree, the corpus is the arbiter, not either program. A case the")
    w("original fails is adjudicated on evidence: either the test is wrong and gets fixed,")
    w("or the original has a defect and this implementation must not copy it.")
    w("")
    w("## The shape of a test")
    w("")
    w("Each case names a fixture font, some editor input, and a list of things that must")
    w("be true of the result — or, for a bad input, the refusal that must come back. Each")
    w("also carries the behavioural claims it covers, from")
    w("[the behaviour map](original-behaviour.md), and a rationale saying why that is the")
    w("right answer.")
    w("")
    w("Every case is labelled with where its authority comes from:")
    w("")
    w("| label | meaning | cases |")
    w("|---|---|---|")
    for label, description in [
        ("spec", "the OpenType specification requires it"),
        ("fonttools", "inherited from fontTools, which the original delegates to"),
        ("slice-ui", "the application's own contract"),
        ("judgement", "a defensible design choice with no external authority"),
    ]:
        w(f"| `{label}` | {description} | {classes.get(label, 0)} |")
    w("")
    w(f"There are **{len(cases)} cases** in total, across {len(by_area)} areas.")
    if needs_feature:
        w(f"{needs_feature} of them require removing overlaps, which the original never")
        w("had; it is expected to fail those, and that is not counted against it.")
    w("")
    w("## Contents")
    w("")
    for area in sorted(by_area):
        w(f"- [{area}](#{area}) — {len(by_area[area])} cases")
    w("")

    for area in sorted(by_area):
        area_cases = by_area[area]
        w(f"## {area}")
        w("")
        if area in AREA_INTROS:
            w(AREA_INTROS[area])
            w("")
        covered = sorted({c for case in area_cases for c in case.get("covers", [])})
        if covered:
            w(f"Covers claims: {', '.join(covered)}.")
            w("")

        for case in sorted(area_cases, key=lambda c: c["id"]):
            w(f"### `{case['id']}`")
            w("")
            w(f"**{case.get('title', '(untitled)')}**")
            w("")
            rationale = case.get("rationale", "").strip()
            w(rationale if rationale else "_No rationale given — this case needs one._")
            w("")
            bits = []
            if case.get("covers"):
                bits.append("covers " + ", ".join(case["covers"]))
            if case.get("class"):
                bits.append(f"authority: `{case['class']}`")
            bits.append(f"fixture: `{case.get('fixture', '?')}`")
            if case.get("original_lacks_feature"):
                bits.append("**the original does not have this feature**")
            expect = case.get("expect", {})
            if expect.get("outcome") == "error":
                wanted = ", ".join(f"`{s}`" for s in expect.get("message_contains", []))
                bits.append(f"expects a refusal mentioning {wanted}")
            w(f"<sub>{' · '.join(bits)}</sub>")
            w("")

    w("## Coverage")
    w("")
    counts = Counter()
    for case in cases:
        for claim in case.get("covers", []):
            counts[claim] += 1
    if titles:
        declared = set(titles)
        missing = sorted(declared - set(counts))
        w(f"The behaviour map declares {len(declared)} claims. "
          f"{len(declared) - len(missing)} of them have at least one case.")
        w("")
        if missing:
            w("Claims with no case yet:")
            w("")
            for claim in missing:
                w(f"- **{claim}** — {titles.get(claim, '')}")
            w("")
    w("| claim | cases | statement |")
    w("|---|---|---|")
    for claim in sorted(counts, key=lambda c: (c[0], int(c[1:]))):
        statement = titles.get(claim, "")
        if len(statement) > 110:
            statement = statement[:107] + "..."
        w(f"| {claim} | {counts[claim]} | {statement} |")
    w("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    cases = load_cases()
    if not cases:
        print("no cases found", file=sys.stderr)
        return 1
    generated = render(cases)

    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            print(f"{OUTPUT} is out of date; re-run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date ({len(cases)} cases)")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print(f"documented {len(cases)} cases in {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
