//! Rebasing a variation "tent" onto a restricted axis.
//!
//! This is the mathematical heart of Level 3 sub-spacing, and it is the part with no
//! Rust equivalent anywhere: given one axis of one tuple variation, described by its
//! support triple `(lower, peak, upper)`, and the new axis limits the user asked for,
//! work out how to express the same contribution over the smaller axis.
//!
//! The answer is not always a single tent. A triangle with part of one side cut off is
//! not a triangle, so a tent sometimes has to be split into two or three, each with its
//! own multiplier for the delta set. It can also collapse into a constant contribution
//! that applies everywhere, which is reported as a `None` tent and is conventionally
//! called the *gain*.
//!
//! This is a direct port of `fontTools.varLib.instancer.solver`, deliberately kept
//! structurally identical to the Python so the two can be diffed by eye when fontTools
//! changes. The case numbering in the comments is theirs. It is checked against
//! fontTools' own test vectors: see `solver_vectors.rs`, which is generated by
//! `tools/gen-solver-vectors.py`.

/// The smallest meaningful step in F2Dot14, used to nudge a tent peak off the axis
/// default when the geometry would otherwise put it exactly there.
pub const EPSILON: f64 = 1.0 / (1 << 14) as f64;

/// A variation support triple: `(lower, peak, upper)`, in normalized coordinates.
pub type Tent = (f64, f64, f64);

/// One output of the solver: a multiplier for the delta set, and the tent it now applies
/// over. A `None` tent means the contribution is unconditional.
pub type Solution = (f64, Option<Tent>);

/// New axis limits, in normalized coordinates, plus the pre-normalization distances.
///
/// The distances are the *user-space* widths of the two halves of the original axis.
/// They are needed because renormalizing a value that crosses the default has to respect
/// how much design space each side actually covered; without them, an axis whose default
/// sits off-centre renormalizes wrongly. See fontTools issue #3177.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct AxisTriple {
    pub min: f64,
    pub default: f64,
    pub max: f64,
    pub distance_negative: f64,
    pub distance_positive: f64,
}

impl AxisTriple {
    /// A triple with the default unit distances, which is right whenever the axis was
    /// normalized symmetrically.
    pub fn new(min: f64, default: f64, max: f64) -> Self {
        Self {
            min,
            default,
            max,
            distance_negative: 1.0,
            distance_positive: 1.0,
        }
    }

    pub fn with_distances(
        min: f64,
        default: f64,
        max: f64,
        distance_negative: f64,
        distance_positive: f64,
    ) -> Self {
        Self {
            min,
            default,
            max,
            distance_negative,
            distance_positive,
        }
    }

    /// Mirror the axis about zero, so that a problem stated on the negative side can be
    /// solved by the positive-side code.
    pub fn reverse_negate(&self) -> Self {
        Self {
            min: -self.max,
            default: -self.default,
            max: -self.min,
            distance_negative: self.distance_positive,
            distance_positive: self.distance_negative,
        }
    }

    /// True when the axis has been pinned to a single location.
    pub fn is_point(&self) -> bool {
        self.min == self.default && self.default == self.max
    }

    /// Map a value in the original normalized space onto the restricted axis, where the
    /// new limits become -1 and +1.
    pub fn renormalize_value(&self, v: f64) -> f64 {
        let AxisTriple {
            min: lower,
            default,
            max: upper,
            distance_negative,
            distance_positive,
        } = *self;
        debug_assert!(lower <= default && default <= upper);

        if v == default {
            return 0.0;
        }
        if default < 0.0 {
            return -self.reverse_negate().renormalize_value(-v);
        }

        // default >= 0 and v != default
        if v > default {
            return (v - default) / (upper - default);
        }
        // v < default
        if lower >= 0.0 {
            return (v - default) / (default - lower);
        }

        // lower < 0 and v < default: the value crosses the axis default, so the two
        // halves have to be weighted by how much design space each one covered.
        let total_distance = distance_negative * -lower + distance_positive * default;
        let v_distance = if v >= 0.0 {
            (default - v) * distance_positive
        } else {
            -v * distance_negative + distance_positive * default
        };
        -v_distance / total_distance
    }
}

fn reverse_negate(t: Tent) -> Tent {
    (-t.2, -t.1, -t.0)
}

/// The scalar a single-axis tent contributes at location `v`.
///
/// This is `fontTools.varLib.models.supportScalar` reduced to one axis, with the
/// OpenType conventions: a peak of zero, or a malformed or default-crossing triple, means
/// the axis does not participate and contributes a factor of 1.
pub(crate) fn support_scalar(v: f64, tent: Tent) -> f64 {
    let (lower, peak, upper) = tent;
    if peak == 0.0 {
        return 1.0;
    }
    if lower > peak || peak > upper {
        return 1.0;
    }
    if lower < 0.0 && upper > 0.0 {
        return 1.0;
    }
    if v == peak {
        return 1.0;
    }
    if v <= lower || upper <= v {
        return 0.0;
    }
    if v < peak {
        (v - lower) / (peak - lower)
    } else {
        (v - upper) / (peak - upper)
    }
}

/// Solve one tent against one axis limit, in the original normalized space.
///
/// fontTools threads a `negative` flag through this recursion. Its only reader lives
/// inside a branch that fontTools has disabled (`if False and ...`, see their issue
/// #3350, where OTS rejected the fonts the branch produced), so it is omitted here. If
/// that branch is ever re-enabled upstream, the flag has to come back with it.
fn solve(tent: Tent, axis_limit: AxisTriple) -> Vec<Solution> {
    let AxisTriple {
        min: axis_min,
        default: axis_def,
        max: axis_max,
        ..
    } = axis_limit;
    let (lower, peak, mut upper) = tent;

    // Mirror the problem so that axis_def <= peak, halving the number of cases.
    if axis_def > peak {
        return solve(reverse_negate(tent), axis_limit.reverse_negate())
            .into_iter()
            .map(|(scalar, t)| (scalar, t.map(reverse_negate)))
            .collect();
    }

    // Case 1: the whole delta set falls outside the new limit, so it can be dropped.
    if axis_max <= lower && axis_max < peak {
        return Vec::new();
    }

    // Case 2: only the peak and the outer bound fall outside the new limit. Pull them in
    // to the new maximum, scale by the tent's value there, and solve what is left.
    if axis_max < peak {
        let mult = support_scalar(axis_max, tent);
        let tent = (lower, axis_max, axis_max);
        return solve(tent, axis_limit)
            .into_iter()
            .map(|(scalar, t)| (scalar * mult, t))
            .collect();
    }

    // lower <= axis_def <= peak <= axis_max

    // The tent's value at the new default becomes an unconditional contribution.
    let gain = support_scalar(axis_def, tent);
    let mut out: Vec<Solution> = vec![(gain, None)];

    // --- the positive side ---

    let out_gain = support_scalar(axis_max, tent);

    if gain >= out_gain {
        // Case 3a: the down-slope crosses below the gain line, so it has to be split.
        // Also the branch taken when both gain and out_gain are zero.
        let crossing = peak + (1.0 - gain) * (upper - peak);

        let loc = (lower.max(axis_def), peak, crossing);
        out.push((1.0 - gain, loc.into()));

        if upper >= axis_max {
            // Case 3a1: one tent is enough.
            let loc = (crossing, axis_max, axis_max);
            out.push((out_gain - gain, loc.into()));
        } else {
            // Case 3a2: two tents, to hold the value down past `upper`.
            // A tent's peak may not sit on the axis default; nudge it.
            if upper == axis_def {
                upper += EPSILON;
            }
            out.push((-gain, Some((crossing, upper, axis_max))));
            out.push((-gain, Some((upper, axis_max, axis_max))));
        }
    } else {
        // Upstream clamps `upper` down to `peak` here when the peak sits exactly at the
        // new maximum. The only code that went on to read `upper` was the disabled
        // Case 3 below, so the clamp has nothing left to affect and is omitted; it has
        // to come back if that branch is ever revived.

        // Case 4: the new limit does not fit, so chop into two tents. fontTools has a
        // Case 3 here that rescales a single tent instead, but it is disabled upstream
        // because OTS rejected the result (fontTools issue #3350), so this is the only
        // live path.
        let loc1 = (axis_def.max(lower), peak, axis_max);
        out.push((1.0 - gain, loc1.into()));

        let loc2 = (peak, axis_max, axis_max);
        // Never emit a Dirac delta.
        if peak < axis_max {
            out.push((out_gain - gain, loc2.into()));
        }
    }

    // --- the negative side ---

    if lower <= axis_min {
        // Case 1neg: the lower bound reaches past the new minimum, so it just gets cut.
        let loc = (axis_min, axis_min, axis_def);
        let scalar = support_scalar(axis_min, tent);
        out.push((scalar - gain, loc.into()));
    } else {
        // Case 2neg: the lower bound sits between the new minimum and the default, so it
        // takes two tents to hold the value down all the way out.
        let mut lower = lower;
        if lower == axis_def {
            lower -= EPSILON;
        }
        out.push((-gain, Some((axis_min, lower, axis_def))));
        out.push((-gain, Some((axis_min, axis_min, lower))));
    }

    out
}

/// Express `tent` under the new axis limits `axis_limit`.
///
/// Both are in the original normalized -1..+1 space; the returned tents are in the
/// *new* normalized space, where the restricted limits map to -1 and +1. Solutions whose
/// scalar came out zero are dropped, since they contribute nothing.
///
/// # Panics
///
/// Panics on inputs that are not valid normalized coordinates, or on a tent with a peak
/// of zero, which by OpenType convention means the axis does not participate and so
/// should never have reached the solver.
pub fn rebase_tent(tent: Tent, axis_limit: AxisTriple) -> Vec<Solution> {
    let AxisTriple {
        min: axis_min,
        default: axis_def,
        max: axis_max,
        ..
    } = axis_limit;
    assert!(
        (-1.0..=1.0).contains(&axis_min)
            && axis_min <= axis_def
            && axis_def <= axis_max
            && axis_max <= 1.0,
        "axis limit {axis_limit:?} is not a sorted normalized triple"
    );

    let (lower, peak, upper) = tent;
    assert!(
        (-2.0..=2.0).contains(&lower) && lower <= peak && peak <= upper && upper <= 2.0,
        "tent {tent:?} is not a sorted triple within -2..+2"
    );
    assert!(
        peak != 0.0,
        "a tent peak of zero should never reach the solver"
    );

    solve(tent, axis_limit)
        .into_iter()
        .filter(|(scalar, _)| *scalar != 0.0)
        .map(|(scalar, t)| {
            let t = t.map(|(a, b, c)| {
                (
                    axis_limit.renormalize_value(a),
                    axis_limit.renormalize_value(b),
                    axis_limit.renormalize_value(c),
                )
            });
            (scalar, t)
        })
        .collect()
}

#[cfg(test)]
#[path = "solver_vectors.rs"]
mod solver_vectors;

#[cfg(test)]
mod tests {
    use super::*;

    /// fontTools compares with `pytest.approx`, whose default relative tolerance is
    /// 1e-6; the vectors carry hand-rounded values like `0.45454545`, so an exact
    /// comparison would fail on the reference data itself.
    const TOLERANCE: f64 = 1e-6;

    fn close(a: f64, b: f64) -> bool {
        (a - b).abs() <= TOLERANCE * a.abs().max(b.abs()).max(1.0)
    }

    #[test]
    fn matches_fonttools_solver_test_vectors() {
        let mut failures = Vec::new();

        for case in solver_vectors::VECTORS {
            let limit = AxisTriple::with_distances(
                case.axis_range.0,
                case.axis_range.1,
                case.axis_range.2,
                case.axis_range.3,
                case.axis_range.4,
            );
            let got = rebase_tent(case.tent, limit);

            let same = got.len() == case.expected.len()
                && got.iter().zip(case.expected.iter()).all(|(g, e)| {
                    close(g.0, e.0)
                        && match (g.1, e.1) {
                            (None, None) => true,
                            (Some(a), Some(b)) => {
                                close(a.0, b.0) && close(a.1, b.1) && close(a.2, b.2)
                            }
                            _ => false,
                        }
                });

            if !same {
                failures.push(format!(
                    "tent {:?} limit {:?}\n     expected {:?}\n     got      {:?}",
                    case.tent, case.axis_range, case.expected, got
                ));
            }
        }

        assert!(
            failures.is_empty(),
            "{} of {} fontTools solver vectors disagree:\n{}",
            failures.len(),
            solver_vectors::VECTORS.len(),
            failures.join("\n")
        );
    }

    #[test]
    fn every_vector_is_actually_exercised() {
        // Guards against the generator silently emitting an empty table.
        assert!(
            solver_vectors::VECTORS.len() >= 30,
            "expected the full fontTools vector set, found {}",
            solver_vectors::VECTORS.len()
        );
    }

    #[test]
    fn support_scalar_matches_the_documented_examples() {
        // From the doctests on fontTools' supportScalar.
        assert!(close(support_scalar(0.2, (0.0, 2.0, 3.0)), 0.1));
        assert!(close(support_scalar(2.5, (0.0, 2.0, 4.0)), 0.75));
        // A peak of zero means the axis does not participate.
        assert_eq!(support_scalar(0.5, (0.0, 0.0, 0.0)), 1.0);
        // A triple that straddles the default also does not participate.
        assert_eq!(support_scalar(0.5, (-1.0, 0.5, 1.0)), 1.0);
    }

    #[test]
    fn renormalize_is_the_identity_on_an_unrestricted_axis() {
        let full = AxisTriple::new(-1.0, 0.0, 1.0);
        for v in [-1.0, -0.5, 0.0, 0.25, 1.0] {
            assert!(close(full.renormalize_value(v), v), "{v}");
        }
    }

    #[test]
    fn renormalize_maps_the_new_limits_onto_plus_minus_one() {
        let limit = AxisTriple::new(0.25, 0.5, 0.75);
        assert!(close(limit.renormalize_value(0.25), -1.0));
        assert!(close(limit.renormalize_value(0.5), 0.0));
        assert!(close(limit.renormalize_value(0.75), 1.0));
    }

    #[test]
    fn pinning_at_the_default_drops_everything() {
        let at_default = AxisTriple::new(0.0, 0.0, 0.0);
        assert!(rebase_tent((0.0, 1.0, 1.0), at_default).is_empty());
    }

    #[test]
    fn a_tent_wholly_outside_the_new_range_is_dropped() {
        let limit = AxisTriple::new(0.1, 0.2, 0.3);
        assert!(rebase_tent((0.3, 0.5, 0.8), limit).is_empty());
    }

    #[test]
    #[should_panic(expected = "peak of zero")]
    fn a_zero_peak_is_a_programming_error() {
        rebase_tent((0.0, 0.0, 0.0), AxisTriple::new(-1.0, 0.0, 1.0));
    }
}
