// @generated by tools/gen-solver-vectors.py -- do not edit by hand.
//
// Test vectors lifted verbatim from fontTools
// Tests/varLib/instancer/solver_test.py at tag 4.62.1:
// https://raw.githubusercontent.com/fonttools/fonttools/4.62.1/Tests/varLib/instancer/solver_test.py
//
// Each entry is one case from upstream's `test_rebaseTent` parametrize table.
// `axis_range` is padded to five fields; upstream defaults the two
// pre-normalization distances to 1 when it writes a three-field range.

/// A solver result: a multiplier, and the tent it applies over.
/// A `None` tent is the unconditional 'gain' term.
pub type Solution = (f64, Option<(f64, f64, f64)>);

/// One case: rebasing `tent` onto `axis_range` must produce `expected`.
pub struct Vector {
    pub tent: (f64, f64, f64),
    pub axis_range: (f64, f64, f64, f64, f64),
    pub expected: &'static [Solution],
}

#[rustfmt::skip]
pub const VECTORS: &[Vector] = &[
    Vector {
        tent: (0.0, 1.0, 1.0),
        axis_range: (0.0, 0.0, 0.0, 1.0, 1.0),
        expected: &[],
    },
    Vector {
        tent: (0.3, 0.5, 0.8),
        axis_range: (0.1, 0.2, 0.3, 1.0, 1.0),
        expected: &[],
    },
    Vector {
        tent: (0.0, 1.0, 1.0),
        axis_range: (0.5, 0.5, 0.5, 1.0, 1.0),
        expected: &[
            (0.5, None),
        ],
    },
    Vector {
        tent: (0.0, 1.0, 1.0),
        axis_range: (-1.0, 0.0, 0.5, 1.0, 1.0),
        expected: &[
            (0.5, Some((0.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 1.0, 1.0),
        axis_range: (-1.0, 0.0, 0.75, 1.0, 1.0),
        expected: &[
            (0.75, Some((0.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.2, 1.0),
        axis_range: (-1.0, 0.0, 0.8, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.0, 0.25, 1.0))),
            (0.25, Some((0.25, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.4, 1.0),
        axis_range: (-1.0, 0.0, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.0, 0.8, 1.0))),
            (0.8333333333333334, Some((0.8, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.25, 1.0),
        axis_range: (-1.0, 0.0, 0.4, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.0, 0.625, 1.0))),
            (0.8, Some((0.625, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.25, 0.3, 1.05),
        axis_range: (0.0, 0.2, 0.4, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.25, 0.5, 1.0))),
            (0.8666666666666667, Some((0.5, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.25, 0.5, 1.0),
        axis_range: (0.0, 0.25, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 1.0),
        axis_range: (0.0, 0.5, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-1.0, Some((0.0, 1.0, 1.0))),
            (-1.0, Some((-1.0, -1.0, 0.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 1.0),
        axis_range: (0.0, 0.5, 0.75, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-0.5, Some((0.0, 1.0, 1.0))),
            (-1.0, Some((-1.0, -1.0, 0.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 1.0),
        axis_range: (0.0, 0.25, 0.8, 1.0, 1.0),
        expected: &[
            (0.5, None),
            (0.5, Some((0.0, 0.45454545, 0.909090909))),
            (-0.1, Some((0.909090909, 1.0, 1.0))),
            (-0.5, Some((-1.0, -1.0, 0.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 2.0),
        axis_range: (0.2, 0.5, 0.8, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-0.2, Some((0.0, 1.0, 1.0))),
            (-0.6, Some((-1.0, -1.0, 0.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 2.0),
        axis_range: (0.2, 0.5, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-0.3333333333333333, Some((0.0, 1.0, 1.0))),
            (-0.6, Some((-1.0, -1.0, 0.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 1.0),
        axis_range: (0.25, 0.25, 0.75, 1.0, 1.0),
        expected: &[
            (0.5, None),
            (0.5, Some((0.0, 0.5, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 1.0),
        axis_range: (0.0, 0.25, 0.5, 1.0, 1.0),
        expected: &[
            (0.5, None),
            (0.5, Some((0.0, 1.0, 1.0))),
            (-0.5, Some((-1.0, -1.0, 0.0))),
        ],
    },
    Vector {
        tent: (0.05, 0.55, 1.0),
        axis_range: (0.0, 0.25, 0.5, 1.0, 1.0),
        expected: &[
            (0.4, None),
            (0.5, Some((0.0, 1.0, 1.0))),
            (-0.4, Some((-1.0, -0.8, 0.0))),
            (-0.4, Some((-1.0, -1.0, -0.8))),
        ],
    },
    Vector {
        tent: (-1.0, -0.55, -0.05),
        axis_range: (-0.5, -0.25, 0.0, 1.0, 1.0),
        expected: &[
            (0.4, None),
            (0.5, Some((-1.0, -1.0, 0.0))),
            (-0.4, Some((0.0, 0.8, 1.0))),
            (-0.4, Some((0.8, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.5, 0.5, 0.5),
        axis_range: (0.5, 0.5, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, None),
        ],
    },
    Vector {
        tent: (0.3, 0.5, 0.7),
        axis_range: (0.1, 0.5, 0.9, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-1.0, Some((0.0, 0.5, 1.0))),
            (-1.0, Some((0.5, 1.0, 1.0))),
            (-1.0, Some((-1.0, -0.5, 0.0))),
            (-1.0, Some((-1.0, -1.0, -0.5))),
        ],
    },
    Vector {
        tent: (0.5, 0.5, 0.5),
        axis_range: (0.25, 0.25, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, Some((1.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.5, 0.5, 0.5),
        axis_range: (0.25, 0.35, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, Some((1.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.5, 0.5, 0.55),
        axis_range: (0.25, 0.35, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, Some((1.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.5, 0.5, 1.0),
        axis_range: (0.5, 0.5, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-1.0, Some((0.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.25, 0.5, 1.0),
        axis_range: (0.5, 0.5, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-1.0, Some((0.0, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.2, 1.0),
        axis_range: (0.0, 0.0, 0.5, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.0, 0.4, 1.0))),
            (0.625, Some((0.4, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 0.5, 1.0),
        axis_range: (-1.0, 0.25, 1.0, 1.0, 1.0),
        expected: &[
            (0.5, None),
            (0.5, Some((0.0, 0.3333333333333333, 0.6666666666666666))),
            (-0.5, Some((0.6666666666666666, 1.0, 1.0))),
            (-0.5, Some((-1.0, -0.2, 0.0))),
            (-0.5, Some((-1.0, -1.0, -0.2))),
        ],
    },
    Vector {
        tent: (0.5, 0.5, 0.5),
        axis_range: (0.0, 0.5, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, None),
            (-1.0, Some((0.0, 0.0001220703, 1.0))),
            (-1.0, Some((0.0001220703, 1.0, 1.0))),
            (-1.0, Some((-1.0, -0.0001220703, 0.0))),
            (-1.0, Some((-1.0, -1.0, -0.0001220703))),
        ],
    },
    Vector {
        tent: (0.0, 1.0, 1.0),
        axis_range: (-1.0, -0.5, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.3333333333333333, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.0, 1.0, 1.0),
        axis_range: (-1.0, -0.5, 1.0, 2.0, 1.0),
        expected: &[
            (1.0, Some((0.5, 1.0, 1.0))),
        ],
    },
    Vector {
        tent: (0.6, 0.7, 0.8),
        axis_range: (-1.0, 0.2, 1.0, 1.0, 1.0),
        expected: &[
            (1.0, Some((0.5, 0.625, 0.75))),
        ],
    },
];
