#!/usr/bin/env python3
"""Generate the Rust test vectors for the sub-space solver.

Question this answers
---------------------
    Does `slice_core::solver::rebase_tent` agree with
    `fontTools.varLib.instancer.solver.rebaseTent` on every case fontTools tests?

`crates/slice-core/src/solver.rs` is a hand port of the fontTools solver. A hand port is
only worth as much as the evidence that it matches, so rather than inventing our own
cases we lift the upstream parametrised test table verbatim and compile it into a Rust
`const`, which `solver.rs`'s `matches_fonttools_solver_test_vectors` test walks.

Usage
-----
    tools/gen-solver-vectors.py                 # fetch from GitHub, write the Rust file
    tools/gen-solver-vectors.py --check         # regenerate and fail if it differs
    tools/gen-solver-vectors.py --from FILE     # use a local copy of solver_test.py

The fontTools version is pinned in FONTTOOLS_TAG below. Bump it, re-run, and commit the
regenerated file together with any solver change it forces; that way the vectors in the
tree always say which upstream release they came from.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

FONTTOOLS_TAG = "4.62.1"
SOURCE_URL = (
    "https://raw.githubusercontent.com/fonttools/fonttools/"
    f"{FONTTOOLS_TAG}/Tests/varLib/instancer/solver_test.py"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "crates" / "slice-core" / "src" / "solver_vectors.rs"


def fetch_source(local: Path | None) -> str:
    if local is not None:
        return local.read_text(encoding="utf-8")
    with urllib.request.urlopen(SOURCE_URL, timeout=60) as response:
        return response.read().decode("utf-8")


def extract_table(source: str) -> list[tuple]:
    """Pull the `tent, axisRange, expected` parametrize table out of the test file.

    The table is a plain Python literal apart from the `pytest.param` wrappers, so it can
    be evaluated with a stub that returns its positional arguments unchanged. We do not
    import fontTools: only the literal data is wanted, not the implementation.
    """
    marker = '"tent, axisRange, expected",'
    start = source.index(marker) + len(marker)
    open_bracket = source.index("[", start)

    # Walk to the matching bracket so nested lists and tuples come along.
    depth = 0
    for i in range(open_bracket, len(source)):
        char = source[i]
        if char in "[(":
            depth += 1
        elif char in "])":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    else:
        raise SystemExit("could not find the end of the parametrize table")

    literal = source[open_bracket:end]

    class _Pytest:
        @staticmethod
        def param(*args, **_kwargs):
            return args

    table = eval(literal, {"pytest": _Pytest, "__builtins__": {}}, {})  # noqa: S307
    if not table:
        raise SystemExit("parametrize table came out empty")
    return table


def rust_float(value) -> str:
    text = repr(float(value))
    if "e" in text or "E" in text or "." in text:
        return text
    return text + ".0"


def rust_tent(tent) -> str:
    return "({})".format(", ".join(rust_float(v) for v in tent))


def render(table: list[tuple]) -> str:
    lines = [
        "// @generated by tools/gen-solver-vectors.py -- do not edit by hand.",
        "//",
        "// Test vectors lifted verbatim from fontTools",
        f"// Tests/varLib/instancer/solver_test.py at tag {FONTTOOLS_TAG}:",
        f"// {SOURCE_URL}",
        "//",
        "// Each entry is one case from upstream's `test_rebaseTent` parametrize table.",
        "// `axis_range` is padded to five fields; upstream defaults the two",
        "// pre-normalization distances to 1 when it writes a three-field range.",
        "",
        "/// One case: rebasing `tent` onto `axis_range` must produce `expected`.",
        "pub struct Vector {",
        "    pub tent: (f64, f64, f64),",
        "    pub axis_range: (f64, f64, f64, f64, f64),",
        "    pub expected: &'static [(f64, Option<(f64, f64, f64)>)],",
        "}",
        "",
        f"pub const VECTORS: &[Vector] = &[",
    ]

    for tent, axis_range, expected in table:
        axis_range = tuple(axis_range) + (1.0,) * (5 - len(axis_range))
        lines.append("    Vector {")
        lines.append(f"        tent: {rust_tent(tent)},")
        lines.append(
            "        axis_range: ({}),".format(
                ", ".join(rust_float(v) for v in axis_range)
            )
        )
        if not expected:
            lines.append("        expected: &[],")
        else:
            lines.append("        expected: &[")
            for scalar, sol_tent in expected:
                rendered = "None" if sol_tent is None else f"Some({rust_tent(sol_tent)})"
                lines.append(f"            ({rust_float(scalar)}, {rendered}),")
            lines.append("        ],")
        lines.append("    },")

    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate and exit non-zero if the committed file is out of date",
    )
    parser.add_argument(
        "--from",
        dest="local",
        type=Path,
        help="read solver_test.py from a local path instead of fetching it",
    )
    args = parser.parse_args()

    table = extract_table(fetch_source(args.local))
    generated = render(table)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(f"{OUTPUT} is out of date; re-run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date ({len(table)} vectors)")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {len(table)} vectors to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
